CREATE USER for_semi IDENTIFIED BY for_semi;

GRANT RESOURCE, CONNECT TO for_semi;
GRANT INSERT ANY TABLE, UPDATE ANY TABLE, DELETE ANY TABLE,
	CREATE VIEW TO for_semi;
GRANT CREATE SESSION TO for_semi;
ALTER USER for_semi quota 10M ON USERS;

SELECT PRIVILEGE FROM DBA_SYS_PRIVS WHERE GRANTEE = 'FOR_SEMI';
SELECT PRIVILEGE FROM DBA_SYS_PRIVS WHERE GRANTEE = 'PUSER1';
SELECT GRANTED_ROLE FROM DBA_ROLE_PRIVS WHERE GRANTEE = 'FOR_SEMI';

CREATE TABLE desire_t(
	prod_name 		VARCHAR2(20)	PRIMARY KEY
  , prod_type		VARCHAR2(20)	NOT NULL
  , prod_price		NUMBER 			NOT NULL
  , reason			VARCHAR2(40)	NOT NULL
  , exp_use			VARCHAR2(10)	NOT NULL
  , des_percentage 	NUMBER			NOT NULL
);

INSERT INTO DESIRE_T VALUES('피어싱', '쥬얼리', 20000, '얼마전에 뚫어서 바꾸고싶음', '중', 60);

SELECT * FROM desire_t; 
DELETE FROM desire_t 
WHERE PROD_PRICE = 30;
DROP TABLE DESIRE_T;

SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'DESIRE_T';

COMMIT;
ROLLBACK;