-- WHERE절이 ORDER보다 먼저 실행되고있다
SELECT ROWNUM
     , EMPLOYEE_ID
     , FIRST_NAME
     , LAST_NAME
     , SALARY
     , COMMISSION_PCT
  FROM EMPLOYEES
 WHERE COMMISSION_PCT IS NOT NULL
   AND ROWNUM <= 10
 ORDER BY SALARY DESC;

-- 정렬한 후에 ROWNUM으로 자른다.
SELECT *
  FROM (SELECT EMPLOYEE_ID
             , FIRST_NAME
             , LAST_NAME
             , SALARY
             , COMMISSION_PCT
          FROM EMPLOYEES
         WHERE COMMISSION_PCT IS NOT NULL
         ORDER BY SALARY DESC)
 WHERE ROWNUM <= 10;

WITH EMP_COM
  AS (SELECT EMPLOYEE_ID
             , FIRST_NAME
             , LAST_NAME
             , SALARY
             , COMMISSION_PCT
          FROM EMPLOYEES
         WHERE COMMISSION_PCT IS NOT NULL
         ORDER BY SALARY DESC)
SELECT * FROM EMP_COM;

SELECT *
  FROM (SELECT FIRST_NAME
             , LAST_NAME
             , SALARY
             , RANK() OVER(ORDER BY SALARY DESC) AS 순위
          FROM EMPLOYEES)
 WHERE 순위 <= 10;

SELECT FIRST_NAME
     , LAST_NAME
     , SALARY
     , RANK() OVER(ORDER BY SALARY DESC) AS 순위
  FROM EMPLOYEES;

SELECT *
  FROM (SELECT FIRST_NAME
             , LAST_NAME
             , SALARY
             , DENSE_RANK() OVER(ORDER BY SALARY DESC) AS 순위
          FROM EMPLOYEES)
 WHERE 순위 <= 10;

SELECT FIRST_NAME
     , LAST_NAME
     , SALARY
     , DENSE_RANK() OVER(ORDER BY SALARY DESC) AS 순위
  FROM EMPLOYEES;
 
 
 
SELECT *
  FROM EMPLOYEES
 WHERE (SALARY, COMMISSION_PCT) IN ((9500, 0.35), (9500, 0.25));


