SELECT * FROM ALL_ALL_TABLES WHERE TABLE_NAME = 'EMPLOYEES';

--관리자계정(XEPDB1)에 권한이 없어서 EMPLOYEES 조회 불가능
SELECT * FROM EMPLOYEES;
--PUSER1에 연결해서 볼수있음(관리자계정일때만)
SELECT * FROM PUSER1.EMPLOYEES;

-- 동의어 만들수 있는 권한주기(관리자)
GRANT CREATE SYNONYM TO PUSER1;
-- 동의어 만들기(PUSER1) -비공개
CREATE SYNONYM EMP FOR EMPLOYEES;

-- 원래 테이블명과 동의어 둘다 사용가능
SELECT * FROM EMP;
SELECT * FROM PUSER1.EMP;

-- PUBLIC 사용해서 권한없는 다른계정도 사용 가능하게 할 수 있다
CREATE PUBLIC SYNONYM EMP FOR PUSER1.EMPLOYEES;
CREATE PUBLIC SYNONYM DEP FOR PUSER1.DEPARTMENTS;

-- DEVADMIN계정에 동의어 SELECT 권한주기(관리자)
GRANT SELECT ON EMP TO DEVADMIN;
GRANT SELECT ON DEP TO DEVADMIN;

SELECT * FROM DEP;
