/*
 * 함수(Function)
 */
CREATE OR REPLACE FUNCTION FUNC_test1(v1 NUMBER) RETURN NUMBER 
IS
BEGIN 
	RETURN v1 * 10;
END;


SELECT CONCAT('Hello ', 'Function') FROM DUAL;

SELECT FUNC_test1(2) FROM DUAL; 



CREATE OR REPLACE FUNCTION FUNC_test2(v1 VARCHAR2) RETURN VARCHAR2 
IS
BEGIN 
	RETURN 'Result : ' || v1;
END;

SELECT FUNC_test2('Hello') FROM DUAL;


CREATE OR REPLACE FUNCTION FUNC_test3(v1 VARCHAR2) RETURN VARCHAR2 
IS
-- 별도의 변수 만들기
	x     NUMBER := 1;
	y     VARCHAR2(10) := 'Hello';
BEGIN 
	-- 로직
	RETURN 'Result : ' || v1 || x || y;
END;

SELECT FUNC_test3('Hello') FROM DUAL;
