DROP TABLE EMP_BOARDS CASCADE CONSTRAINTS;
DROP SEQUENCE EMP_BOARDS_SEQ;

CREATE TABLE EMP_BOARDS (
	, ID NUMBER NOT NULL
	, TITLE VARCHAR2(100) NOT NULL
	, CONTENT VARCHAR2(2000)
	, EMPID NUMBER NOT NULL
	, CREATEDATE DATE DEFAULT(SYSDATE)
	, VIEW_CNT NUMBER DEFAULT(0)
	, "LIKE" NUMBER DEFAULT(0)
	, CONSTRAINT EMP_BOARDS_ID_PK PRIMARY KEY (ID)
	, CONSTRAINT EMP_BOARDS_EMP_ID_FK FOREIGN KEY(EMPID) REFERENCES EMPLOYEES(EMPLOYEE_ID)
);

SELECT * FROM EMP_BOARDS;

-- 기존 테이블의 데이터를 유지하고 싶다면 이 구문을 실행해서 수정하세요.
-- ALTER TABLE EMP_BOARDS ADD LIKE_CNT NUMBER DEFAULT(0);
-- ALTER TABLE EMP_BOARDS ADD "LIKE" NUMBER DEFAULT(0);

CREATE SEQUENCE EMP_BOARDS_SEQ NOCACHE;

INSERT INTO EMP_BOARDS VALUES(EMP_BOARDS_SEQ.NEXTVAL, '테스트 제목', '테스트 내용', 100, SYSDATE);
